# Generated by Django 2.2.5 on 2020-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('book_price', models.FloatField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('book_desc', models.CharField(max_length=30)),
                ('book_status', models.CharField(max_length=30)),
                ('book_pic', models.ImageField(default='None Selected', upload_to='img/')),
                ('book_date', models.CharField(max_length=30)),
                ('book_class', models.CharField(max_length=30)),
                ('book_category', models.CharField(choices=[('Premium', 'Premium'), ('Old', 'Old')], max_length=1)),
            ],
        ),
    ]
