# Generated by Django 2.2.5 on 2020-05-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200519_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_category',
        ),
        migrations.AddField(
            model_name='book',
            name='book_branch',
            field=models.CharField(choices=[('ALL', 'ALL'), ('CSE', 'CSE'), ('EE', 'EE'), ('EI', 'EI'), ('ME', 'ME'), ('PE', 'PE'), ('ECE', 'ECE')], default='ALL', max_length=40),
        ),
        migrations.AddField(
            model_name='book',
            name='book_tag',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Story', 'Story')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_class',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Old', 'Old')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('old', 'old'), ('new', 'new')], max_length=20),
        ),
    ]
