# Generated by Django 2.2.5 on 2020-05-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200522_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cart',
            field=models.CharField(choices=[('NONE', 'NONE'), ('ADDED', 'ADDED')], default='NONE', max_length=10),
        ),
    ]
