# Generated by Django 2.2.5 on 2020-05-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
