# Generated by Django 2.2.5 on 2020-05-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField(default=None)),
                ('address', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=1)),
            ],
        ),
    ]
