# Generated by Django 2.2.5 on 2020-05-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
